version: '3.1'

services:
  database:
    container_name: bbb_api_development
    image: mysql:8.0.28
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 8dukpJfd8w
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - $PWD/docker/mysql:/var/lib/mysql