version: '2.4'

services:
  mysql:
    container_name: challenge-mysql
    image: mysql:8.0-debian
    command: --default-authentication-plugin=mysql_native_password # mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 8dukpJfd8w
    ports:
      - 3307:3306
    volumes:
      - $PWD/mysql/init:/docker-entrypoint-initdb.d
      - $PWD/tmp/mysql-data:/var/lib/mysql
    networks:
      plin_plin:
        ipv4_address: 172.20.0.2

  redis: 
    container_name: challenge-redis
    image: redis:6.2-alpine
    ports: 
      - 6379:6379
    volumes: 
      - $PWD/tmp/redis-data:/data
    networks:
      plin_plin:
        ipv4_address: 172.20.0.4

  challenge-api: 
    container_name: challenge-api
    image: globo-challenge-api:1.0
    ports:
      - 3000:3000
      - 9394:9394
    depends_on:
      - mysql
      - redis
    volumes: 
      - $PWD/../api:/var/www/app/current
    networks:
      plin_plin:
        ipv4_address: 172.20.0.8

  challenge-client: 
    container_name: challenge-client
    image: globo-challenge-client:1.0
    ports:
      - 80:80
    depends_on:
      - challenge-api
    volumes: 
      - $PWD/../client:/app
    networks:
      plin_plin:
        ipv4_address: 172.20.0.10

  prometheus: 
    container_name: prometheus
    image: prom/prometheus:v2.34.0
    ports:
      - 9090:9090
    volumes:
      - $PWD/prometheus/:/etc/prometheus/
      - $PWD/tmp/prometheus_data:/prometheus
    networks:
      plin_plin:
        ipv4_address: 172.20.0.21

  grafana: 
    container_name: grafana
    image: grafana/grafana:8.4.4
    ports:
      - 81:3000
    depends_on:
      - prometheus
    volumes: 
      - $PWD/grafana/provisioning/:/etc/grafana/provisioning/
      - $PWD/tmp/grafana-data:/var/lib/grafana
    env_file:
      - ./grafana/config.monitoring
    networks:
      plin_plin:
        ipv4_address: 172.20.0.23

networks:
  plin_plin:
    ipam:
      config:
        - subnet: 172.20.0.0/24