version: '2.4'

services:
  mysql:
    container_name: challenge-mysql
    image: mysql:8.0-debian
    command: --default-authentication-plugin=mysql_native_password # mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 8dukpJfd8w
    ports:
      - 3306:3306
    volumes:
      - $PWD/mysql/init:/docker-entrypoint-initdb.d
      - $PWD/tmp/mysql-data:/var/lib/mysql
    networks:
      plin_plin:
        ipv4_address: 172.20.0.2

  redis: 
    container_name: challenge-redis
    image: redis:6.2-alpine
    ports: 
      - 6379:6379
    volumes: 
      - $PWD/tmp/redis-data:/data
    networks:
      plin_plin:
        ipv4_address: 172.20.0.4

  challenge-api: 
    container_name: challenge-api
    image: globo-challenge-api:1.0
    ports:
      - 80:3000
    depends_on:
      - mysql
      - redis
    volumes: 
      - $PWD/../api:/var/www/app/current
    networks:
      plin_plin:
        ipv4_address: 172.20.0.8

networks:
  plin_plin:
    ipam:
      config:
        - subnet: 172.20.0.0/24