#!/bin/bash

apt-get update -qq

apt-get install -y vim \
    sudo \
    build-essential \
    libpq-dev \
    net-tools \
    default-mysql-client \
    git \
    imagemagick

gem install bundler && gem update --system

gem install rails -v 6.1.5
